import { HWT_URL } from '@/config/site';
import type { Dim, Question } from './types';

export const DIMS: Dim[] = [
  { id:'body',      label:'Body Health',           icon:'💪', type:'health', barColor:'bg-teal-500',   textColor:'text-teal-400',   description:'Fitness, weight, exercise, daily movement' },
  { id:'nutrition', label:'Nutrition',             icon:'🥗', type:'health', barColor:'bg-green-500',  textColor:'text-green-400',  description:'Diet quality, hydration, meal habits' },
  { id:'mind',      label:'Mental Wellness',       icon:'🧘', type:'health', barColor:'bg-purple-500', textColor:'text-purple-400', description:'Stress, sleep quality, emotional balance' },
  { id:'savings',   label:'Savings & Investments', icon:'💰', type:'wealth', barColor:'bg-amber-500',  textColor:'text-amber-400',  description:'Savings rate, emergency fund, investing' },
  { id:'debt',      label:'Debt & Expenses',       icon:'🧹', type:'wealth', barColor:'bg-orange-500', textColor:'text-orange-400', description:'Debt load, budget, expense control' },
  { id:'future',    label:'Financial Future',      icon:'🚀', type:'wealth', barColor:'bg-blue-500',   textColor:'text-blue-400',   description:'Retirement, insurance, long-term goals' },
];

const D: Record<string, Dim> = Object.fromEntries(DIMS.map(d => [d.id, d]));

export const QUESTIONS: Question[] = [
  // ── BODY ──────────────────────────────────────────────────────────────────
  { id:'exercise', dimension:D.body, weight:3,
    text:'How many days per week do you do intentional physical activity?',
    subtitle:'Brisk walk, gym, yoga, sports — anything that raises your heart rate',
    options:[{icon:'🔥',label:'5 or more days',value:100},{icon:'💪',label:'3–4 days',value:75},{icon:'🚶',label:'1–2 days',value:40},{icon:'😴',label:'Rarely or never',value:10}] },
  { id:'bmi', dimension:D.body, weight:3,
    text:'How would you describe your current weight and fitness?',
    hwtLink:{label:'Check your BMI',url:`/tools/health/bmi`},
    options:[{icon:'🏃',label:'Healthy weight, exercise regularly',value:100},{icon:'🚶',label:'Slightly overweight but active',value:75},{icon:'😐',label:'Overweight and mostly sedentary',value:40},{icon:'😟',label:'Significantly over/underweight, little activity',value:15}] },
  { id:'sleep_hrs', dimension:D.body, weight:2,
    text:'How many hours of sleep do you typically get on weeknights?',
    hwtLink:{label:'Sleep Calculator',url:`/tools/health/sleep`},
    options:[{icon:'✅',label:'7–9 hours consistently',value:100},{icon:'🟡',label:'6–7 hours most nights',value:65},{icon:'🟠',label:'5–6 hours — often tired',value:35},{icon:'🔴',label:'Under 5 hours or very irregular',value:10}] },
  { id:'steps', dimension:D.body, weight:2,
    text:'How many steps do you take on a typical day?',
    subtitle:'Including work, home, and daily activities',
    hwtLink:{label:'Steps Calculator',url:`/tools/health/steps`},
    options:[{icon:'🏅',label:'10,000+ steps',value:100},{icon:'👟',label:'7,000–10,000 steps',value:75},{icon:'🚗',label:'4,000–7,000 steps',value:45},{icon:'🛋️',label:'Under 4,000 — mostly sedentary',value:15}] },

  // ── NUTRITION ─────────────────────────────────────────────────────────────
  { id:'diet', dimension:D.nutrition, weight:3,
    text:'How would you describe your typical daily diet?',
    options:[{icon:'🥦',label:'Mostly whole foods, vegetables, protein, minimal processed food',value:100},{icon:'🥗',label:'Mix of healthy and processed — I try to eat well',value:70},{icon:'🍕',label:'Mostly convenience food with occasional vegetables',value:35},{icon:'🍟',label:'Lots of fast food, sugary drinks, minimal cooking',value:10}] },
  { id:'water', dimension:D.nutrition, weight:2,
    text:'How much water do you drink daily?',
    subtitle:'General guideline: 35 ml per kg of bodyweight',
    hwtLink:{label:'Water Calculator',url:`/tools/health/water`},
    options:[{icon:'💧',label:'2.5 litres or more',value:100},{icon:'🥤',label:'1.5–2.5 litres',value:70},{icon:'😐',label:'1–1.5 litres',value:40},{icon:'☕',label:'Less than 1 litre — mostly tea or soft drinks',value:15}] },
  { id:'meals', dimension:D.nutrition, weight:2,
    text:'How regular are your meals? Do you skip meals often?',
    options:[{icon:'⏰',label:'Regular meals at consistent times, rarely skip',value:100},{icon:'🕐',label:'Mostly regular with occasional skipping',value:70},{icon:'⚡',label:'Skip meals often or eat at highly irregular times',value:35},{icon:'🚫',label:'No real meal pattern — eat whenever available',value:10}] },
  { id:'protein', dimension:D.nutrition, weight:2,
    text:'How often do you consciously include protein in meals?',
    subtitle:'Eggs, chicken, dal, paneer, soy, fish, legumes',
    hwtLink:{label:'Macro Calculator',url:`/tools/health/macros`},
    options:[{icon:'🥩',label:'Every meal — I plan or track protein',value:100},{icon:'🍳',label:'Most meals include some protein',value:70},{icon:'🤔',label:'Rarely think about protein',value:35},{icon:'❌',label:'My diet is very low in protein',value:10}] },

  // ── MIND ──────────────────────────────────────────────────────────────────
  { id:'stress', dimension:D.mind, weight:3,
    text:'How would you rate your average daily stress level?',
    subtitle:'1 = very calm, 10 = extremely stressed',
    options:[{icon:'😌',label:'1–3 — Low stress, feel in control most days',value:100},{icon:'😊',label:'4–5 — Moderate stress, manageable',value:70},{icon:'😰',label:'6–7 — High stress, affects sleep or mood often',value:35},{icon:'😫',label:'8–10 — Chronic, overwhelming stress daily',value:10}] },
  { id:'wakeup', dimension:D.mind, weight:3,
    text:'How refreshed do you feel when you wake up?',
    options:[{icon:'⚡',label:'Alert and energised — well rested',value:100},{icon:'☕',label:'Okay after coffee — not bad',value:70},{icon:'😴',label:'Usually tired and groggy for hours',value:35},{icon:'🪫',label:'Exhausted regardless of sleep duration',value:10}] },
  { id:'social', dimension:D.mind, weight:2,
    text:'How connected do you feel to friends, family, or community?',
    options:[{icon:'🤝',label:'Strong connections — people I can rely on',value:100},{icon:'😊',label:'Some connections, but could be stronger',value:65},{icon:'😐',label:'Mostly isolated — limited social contact',value:30},{icon:'😔',label:'Very lonely — rarely interact meaningfully',value:10}] },
  { id:'screens', dimension:D.mind, weight:1,
    text:'How many hours of recreational screen time per day?',
    subtitle:'Phone/TV outside of work',
    options:[{icon:'📵',label:'Under 2 hours',value:100},{icon:'📱',label:'2–4 hours',value:70},{icon:'📺',label:'4–6 hours',value:40},{icon:'😵',label:'Over 6 hours — phone or TV most of the day',value:15}] },

  // ── SAVINGS ───────────────────────────────────────────────────────────────
  { id:'save_rate', dimension:D.savings, weight:3,
    text:'What % of monthly income do you save or invest?',
    subtitle:'Include SIP, EPF, PPF, FD, stocks — any savings',
    hwtLink:{label:'Savings Goal Calculator',url:`/tools/finance/savings-goal`},
    options:[{icon:'🏆',label:'Over 30% — aggressive saver',value:100},{icon:'💪',label:'20–30% — strong saver',value:80},{icon:'😊',label:'10–20% — moderate saver',value:55},{icon:'😬',label:'5–10% — minimal saving',value:30},{icon:'😟',label:'Under 5% or nothing saved',value:5}] },
  { id:'emergency', dimension:D.savings, weight:3,
    text:'Do you have an emergency fund?',
    options:[{icon:'🛡️',label:'6+ months of expenses in liquid savings',value:100},{icon:'✅',label:'3–6 months of expenses',value:75},{icon:'⚠️',label:'1–3 months — not quite enough',value:45},{icon:'🚨',label:'No emergency fund at all',value:5}] },
  { id:'invest', dimension:D.savings, weight:2,
    text:'How consistent is your investing habit?',
    subtitle:'SIP, mutual funds, stocks, index funds, NPS',
    hwtLink:{label:'SIP Calculator',url:`/tools/finance/sip`},
    options:[{icon:'🤖',label:'Automated — invested every month without thinking',value:100},{icon:'📅',label:'Manual but consistent — invest most months',value:70},{icon:'🎲',label:'Irregular — invest only when I remember',value:35},{icon:'❌',label:'Not investing yet',value:5}] },
  { id:'networth', dimension:D.savings, weight:2,
    text:'Do you know your approximate net worth?',
    subtitle:'Total assets minus total liabilities',
    hwtLink:{label:'Net Worth Calculator',url:`/tools/finance/net-worth`},
    options:[{icon:'📊',label:'Yes — I track it quarterly or more',value:100},{icon:'🤔',label:'Roughly — I have a general idea',value:60},{icon:'❓',label:'Not really — I have no idea',value:20},{icon:'😬',label:'My liabilities likely exceed my assets',value:5}] },

  // ── DEBT ──────────────────────────────────────────────────────────────────
  { id:'debt_load', dimension:D.debt, weight:3,
    text:'What is your total debt situation?',
    hwtLink:{label:'Debt Payoff Calculator',url:`/tools/finance/debt-payoff`},
    options:[{icon:'🎉',label:'Completely debt free',value:100},{icon:'🏠',label:'Only a home loan — no high-interest debt',value:80},{icon:'⚠️',label:'Home loan plus some manageable loans',value:50},{icon:'🔴',label:'Significant credit card or personal loan debt',value:15},{icon:'🚨',label:'Struggling to make minimum payments',value:5}] },
  { id:'cashflow', dimension:D.debt, weight:3,
    text:'After all expenses and EMIs, how much income is left over?',
    hwtLink:{label:'Budget Calculator',url:`/tools/finance/budget`},
    options:[{icon:'💚',label:'Over 40% left — very comfortable',value:100},{icon:'✅',label:'25–40% left — healthy buffer',value:75},{icon:'🟡',label:'10–25% left — tight but managing',value:45},{icon:'🔴',label:'Under 10% — paycheck to paycheck',value:10}] },
  { id:'impulse', dimension:D.debt, weight:2,
    text:'How often do you make impulsive purchases you later regret?',
    options:[{icon:'🧘',label:'Rarely — I think before I buy',value:100},{icon:'😊',label:'Occasionally, but not seriously',value:70},{icon:'😬',label:'Often — I regularly overspend',value:30},{icon:'💸',label:'Very often — serious spending problem',value:5}] },
  { id:'budget', dimension:D.debt, weight:2,
    text:'Do you have a monthly budget or spending plan?',
    options:[{icon:'📋',label:'Yes — detailed budget I actually follow',value:100},{icon:'🗒️',label:'Rough plan in my head that I mostly follow',value:65},{icon:'🤷',label:'No budget — I spend as I go',value:25},{icon:'😱',label:'No budget and often surprised by spending',value:5}] },

  // ── FUTURE ────────────────────────────────────────────────────────────────
  { id:'retire', dimension:D.future, weight:3,
    text:'How prepared are you for retirement?',
    hwtLink:{label:'Retirement Calculator',url:`/tools/finance/retirement`},
    options:[{icon:'🏆',label:'On track — I know my corpus target and meeting it',value:100},{icon:'💪',label:'Saving for retirement but no specific target',value:65},{icon:'😬',label:'Not really saving — just EPF',value:30},{icon:'😟',label:'Not thinking about retirement at all',value:5}] },
  { id:'insurance', dimension:D.future, weight:3,
    text:'What insurance coverage do you have?',
    subtitle:'Health insurance and term life are the two critical ones',
    options:[{icon:'🛡️',label:'Both adequate health AND term life insurance',value:100},{icon:'🏥',label:'Only health insurance — no term life yet',value:65},{icon:'📋',label:'Only basic employer coverage',value:30},{icon:'🚨',label:'No meaningful insurance coverage',value:5}] },
  { id:'fire_goal', dimension:D.future, weight:2,
    text:'Do you have a financial independence goal?',
    subtitle:'A specific amount that would make work optional',
    hwtLink:{label:'FIRE Calculator',url:`/tools/finance/fire`},
    options:[{icon:'🎯',label:'Yes — specific number, timeline, and a plan',value:100},{icon:'💭',label:'I have thought about it but no specific plan',value:55},{icon:'🤔',label:'Never thought about financial independence',value:20},{icon:'😮',label:'I live day to day — future feels uncertain',value:5}] },
  { id:'tax', dimension:D.future, weight:2,
    text:'Do you actively optimise your taxes?',
    subtitle:'80C, 80D, HRA, NPS 80CCD(1B) etc.',
    hwtLink:{label:'Income Tax Calculator',url:`/tools/finance/income-tax`},
    options:[{icon:'💡',label:'Yes — I maximise all relevant deductions',value:100},{icon:'📝',label:'I use 80C and some others — not fully optimised',value:65},{icon:'🤷',label:'I only submit what HR asks for',value:25},{icon:"❌",label:"I don't use any deductions",value:5}] },
];

export const ARTICLES: Record<string, { title: string; slug: string }[]> = {
  body:      [{title:'How to Lose Weight Without Starving',slug:'how-to-lose-weight-without-starving'},{title:'Heart Rate Zones: Train Smarter',slug:'heart-rate-zones-training'}],
  nutrition: [{title:'Protein: How Much You Really Need',slug:'protein-complete-guide'},{title:'TDEE: The Number Every Diet Depends On',slug:'understanding-tdee'}],
  mind:      [{title:'Stress Management: What Actually Works',slug:'stress-management-science'},{title:'The Science of Sleep',slug:'sleep-science-complete-guide'}],
  savings:   [{title:'How to Invest Your First Salary',slug:'how-to-invest-first-salary'},{title:'SIP vs Lump Sum: What Wins?',slug:'sip-vs-lump-sum'}],
  debt:      [{title:'How to Pay Off Debt Fast',slug:'debt-payoff-complete-guide'},{title:'The 50/30/20 Budget: Fixed for India',slug:'budgeting-50-30-20-india'}],
  future:    [{title:'Retirement Planning in India',slug:'retirement-planning-india'},{title:'FIRE in India: Is It Realistic?',slug:'fire-movement-india'}],
};
